### ISSUE TITLE
how to put pdf in the repo 

### ISSUE THREAD

**Issue by jkingslake** [shrink/actions-document-publish#12]
Thanks for a useful tool.

I have it working using your first example which results in a pdf uploaded as an artifact. 

I was wondering how to instead end up with the pdf in the repo. 

I am working on this here: https://github.com/ldeo-glaciology/ITGC-field-doc/tree/auto-pdf

Thanks!

**Comment by shrink** [comment]
@jkingslake I'm glad to hear it's helpful!

The action creates a file called `document.pdf` in a directory called `.publish-docs` so if you'd like to commit this file back to the repository then you could use an action like [Copy file](https://github.com/marketplace/actions/copy-file) to move it to your desired place, and then [Add & Commit](https://github.com/marketplace/actions/add-commit) to push it to the branch.

For example, adapting your current Workflow:

```yaml
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'title.md index.md'
      - uses: canastro/copy-file-action@master
        with:
          source: ".publish-docs/document.pdf"
          target: "my-pdf-name.pdf"
      - uses: EndBug/add-and-commit@v7
        with:
          add: "my-pdf-name.pdf" # same as `target` in the previous step
          default_author: github_actions
```

note: I haven't tested that, but it should work. Let me know if you run into any issues :)
