### ISSUE TITLE
Specify output filename

### ISSUE THREAD

**Issue by SharkFourSix** [shrink/actions-document-publish#14]
How do you specify the output name. I need to specify the name myself because I want to use the file in another file which in not part of the build steps.

**Comment by shrink** [comment]
Unfortunately, this action doesn't support specifying the output file name. I made this action quite a while ago and there are a few things to improve, that's one of them. For now, you can add your own step where you run a shell command to rename the file, e.g:

```yaml
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'documents/front.md documents/examples/**/*.md documents/back.md'
      - run: mv ${{ steps.publish-document.outputs.pdf }} your-file-name.pdf
```
